account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",success_url='password_reset_email_confirm',email_template_name='account/user/password_reset_email.html',form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',success_url='/account/password_reset_complete/', form_class=PwdResetConfirmForm),name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

poultry_farm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contacts', views.contacts, name='contacts'),
    path('lessons', views.lessons, name='lessons'),
    
    path('products', views.all_products, name='all_products'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),

    path('quality', views.quality, name='quality'),
    path('dashboard', views.dashboard, name='dashboard'),
        #add item
    path('add-category',views.AddCategory.as_view(), name='add-category'),
    path('add-product',views.AddProduct.as_view(), name='add-product'),
    
]
# to save media files during development
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# class Appuser(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='appusers')
#     USET_TYPES = (
#         ('A', 'Admin'),
#         ('C', 'Customer')
#     )
#     GENDER_CHOICES = (
#         ('M', 'MALE'),
#         ('F', 'FEMALE'),
#         ('O','OTHER')
#     )
#     user_type = models.CharField(max_length=1,choices=USET_TYPES, default='C')
#     gender = models.CharField(max_length=1,choices=GENDER_CHOICES,default='F')
#     mobile = models.PositiveIntegerField(null=True, blank=True)
#     address = models.CharField(max_length=500,null=True,blank=True)
#     city = models.CharField(max_length=250, null=True, blank=True)
#     pincode = models.PositiveIntegerField(null=True, blank=True)

#     def __str__(self):
#         return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


# def subcategory_image(instance, filename):
#     upload_to = '{}_files/'.format(instance.category.name,instance.name)
#     ext = filename.split('.')[-1]

#     if instance.name:
#         filename = '{}_image.{}'.format(instance.name,ext)
#     return os.path.join(upload_to, filename)

# class SubCategory(models.Model):
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     name = models.CharField(max_length=100)
#     image = models.ImageField(upload_to=subcategory_image, null=True, blank=True)

#     def __str__(self):
#         return str(self.category.name)+ '-' + str(self.name)

# class Animal(models.Model):
#     name = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name

# class Size(models.Model):
#     subCategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, related_name='subcategorySizes')
#     size = models.CharField(max_length=100)

#     def __str__(self):
#         return str(self.subCategory.name) + '-' + str(self.size)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from multiprocessing import context
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Category, Product
from django.contrib import messages
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator


def home(request):
    return render(request, 'store/home.html')

def all_products(request):
    products = Product.products.all()
    return render(request, 'store/products/products.html', {'products': products})


def dashboard(request):
    return render(request, 'store/dashboard.html')

def about(request):
    return render(request, 'store/about.html')

def contacts(request):
    return render(request, 'store/contacts.html')

def equipment(request):
    return render(request, 'store/equipment.html')

def lessons(request):
    return render(request, 'store/lessons.html')

def products(request,category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

def quality(request):
    return render(request, 'store/quality.html')

def eggs(request):
    products = Product.objects.all()
    return render(request, 'store/eggs.html',{'products': products})


# Products
class CategoryView(View):
    def get(self, *args, **kwargs):
        context={'i':range(0,16)}
        return render(self.request, 'store/products.html')

#add views
class AddCategory(SuccessMessageMixin,CreateView):
    model = Category
    fields = ('__all__')
    template_name = 'store/add-category.html'
    success_message = "Category was added successfully"

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('store:add-category')

class AddProduct(SuccessMessageMixin,CreateView):
    model = Product
    fields = ('__all__')
    template_name = 'store/add-product.html'
    success_message = "Product was added successfully"

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('store:add-product')

#####################################################################################################
def categories(request):
    return {
        'categories': Category.objects.all()
    }

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})

templates/store/about.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

<main>
    <div class="row mt-4 pt-5 align-item-center justify-content-center">
        <div class="col-xs-2 col-md-5 col-lg-4">
            <div class="d-flex flex-nowrap" style="margin-bottom:70px">
                <div class="d-flex flex-column flex-shrink-0 p-3" style="background-color: #06283D;width: 280px; margin-top:10px;">
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li class="nav-item text-white">
                            <a href="#" class="nav-link">Our Company</a>
                        </li><hr class="text-white">
                        <li>
                            <a href="#" class="nav-link text-white">Our Mission</a>
                        </li><hr class="text-white">
                    </ul>
                </div>
            </div>
        </div>
        <div class="row col-xs-7 col-md-7 col-lg-7">   
            <h1>Poultry Of The Highest Quality</h1>
            <hr class="bg-dark mt-2 d-inline-block mx-auto" style="width: 660px; height:3px;">
            <p class="text-muted">Dolly farm is a high quality driven farm, established in 2022. We pride ouselves for giving our customers best quality products from poultry farming equipment
                to the actual poultry products from our own farm. currently hiring 15 employees in the community it's based and looking to expand as soon as possible. We 
                also offer training on poultry farming, if you are around the area feel free to come in and get to know more about us. 
            </p>
            <img class="img-responsive img-fluid max-width: 100%" style="height:450px;" src="{% static "images/Chickens1.jpg" %}">
            <div class="container text-center mt-5">
                <h1 class="mb-0">Meet our Team</h1><span>This is our dedicated managment team, they keep the farm opperating in good conditions in all times.</span></div>
            <div class="container mt-3" style="margin-bottom:50px">
                <div class="row">
                    <div class="col-md-4">
                        <div class="bg-white p-3 text-center rounded box"><img class="img-responsive rounded-circle" src="https://i.imgur.com/uppKNuF.jpg" width="90" height="100">
                            <h5 class="mt-3 name">Samuel Plamer</h5><span class="work d-block">Happy Chickens</span><span class="work d-block">Founder</span>
                            <div class="mt-4 about"><span>is a long established fact that eader&nbsp; will be distracted by the readable content.</span></div>
                            <div class="mt-4">
                                <h6 class="v-profile">View Profile</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bg-white p-3 text-center rounded box"><img class="img-responsive rounded-circle" src="https://i.imgur.com/oJmLthK.jpg" width="90">
                            <h5 class="mt-3 name">Nancy Markus</h5><span class="work d-block">Happy Chickens</span><span class="work d-block">CEO</span>
                            <div class="mt-4 about"><span>is a long established fact that eader&nbsp; will be distracted by the readable content.</span></div>
                            <div class="mt-4">
                                <h6 class="v-profile">View Profile</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bg-white p-3 text-center rounded box"><img class="img-responsive rounded-circle" src="https://i.imgur.com/HFpxxJz.jpg" width="90">
                            <h5 class="mt-3 name">Martha Col</h5><span class="work d-block">Happy Chickens</span><span class="work d-block">Manager</span>
                            <div class="mt-4 about"><span>is a long established fact that eader&nbsp; will be distracted by the readable content.</span></div>
                            <div class="mt-4">
                                <h6 class="v-profile">View Profile</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container mt-5">
            <div class="mb-5">
                <h2 class="text-center ">Our Values</h2>
                <h4><strong>MISSION:</strong></h4> To generate more wealth in the hands of small poultry farmers by improving their poultry skills and capacities and by demonstrating 
                    new ways in which they can better manage their available resources. To bring about changes in the lives of the people in the town by giving them jobs and
                    giving training to those willing.
                    <p></p>
                <p><strong>VISION:</strong>To promote sustainable agro-based strategies in order to improve the livelihood of rural poor peoples in general and resource poor farmersin particular.
                    To increase the rural income through improvement of:
                    Agricultural development
                    Better Veterinary service
                    Animal husbandry productivity
                    Aquaculture and fisheries management and production
                    Providing training to unemployed youth and women in particular.
                </p>
              </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/store/add-category.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block content %}
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                Dolly & Sabbi
            </div>
            <div class="list-group list-group-flush my-3">
                  <span class="fs-5 fw-bold px-4"> Dashboard </span>
                <a href="{% url 'store:add-category' %}" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Category </span>
                </a>
                <a href="{% url 'store:add-product' %}" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Product </span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Store Details </span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Contact Info </span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Legal Info </span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text">
                    <span class="px-4">Reply Mails </span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    <span class="fs-5 fw-bold px-2">Orders</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-transparent text-danger fw-bold">
                    <i class="bi bi-power"></i></i>Logout</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>
            </nav>

            <div class="container-fluid px-4">
                <hr class="bg-dark mt-2 mb-2 d-inline-block mx-auto" style="width: 100%; height:3px;">               
                <div class="p-2">
                    <h3>Add Category</h3>
                    <hr class="bg-dark mt-2 mb-2 d-inline-block mx-auto" style="width: 100%; height:1px;">

                    {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}" {% endif %} style="list-style-type:none !important;">
                        {{message}}
                    </li>
                    {% endfor %}

                    <form action="" style="width:50%;" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input type="submit" class="btn-warning go-back-btn h3-white mt-3">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
</body>
{% endblock %}

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<main>
  <section class="container py-5">
    <div id="hero">
      <video loop muted autoplay preload="auto" >
        <source src="{% static "hero/compressed.mp4" %}" type="video/mp4">Your browser does not support the video tag.  
      </video>
      <div class="caption">
        <div class="row py-lg-5 text-align-center">
          <div class="mx-auto">
            <h1 class="h1 fw-bold" style="color:#FF9F29">Only <br><span style="color:#FFEA11">The Best Poultry Products.<span></h1>
              <p class="lead text-white">The best poultry you can find around the world, a happy chicken will always lay 
                more eggs, the more the eggs the lesser the price. To make an online purchase please create an account below</p>
              <p>
                <a href="{% url 'account:register'%}" class="btn btn btn-warning my-2 text-dark">Make an account</a>
              </p>
          </div>
        </div>
      </div>
    </div>
    <div class="container px-4 py-5" id="home">
      <br><br><br><br>
      <div class="row featurette py-5">
        <div class="col-md-7">
          <h1 class="display-3 fw-bold text-dark">Welcome</h1>
          <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 200px; height:3px;">
          <p class="lead"><span>Welcome to Dolly and Sabby where we strive to produce the best poultry products, we also offer poultry farming 
            equipment and online or facility training on poultry farming.</span></p>
          <br><br>
        </div>
        <div class="col-md-5">
          <img class="img-responsive img-fluid" style="width: 450px; height:350px;" src="{% static "images/chicks.jpg" %}">
        </div>
      </div>
    </div>
    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <div class="row g-4 row-cols-1 row-cols-lg-2" id="popular">
          <div class="col d-flex align-items-start">
            <div>
              <h2>Popular Products</h2>
                <p>
                  <ul style="color: #f5ba17;">
                    <li>Chickens</li>
                    <li>Chicks</li>
                    <li>Eggs(6s, 12s, 18s, 30s, and 60s)</li>
                    <li>Farming equipments</li>
                    <li>Chicken Food</li>
                  </ul>
                </p>
                <a href="/products" class="btn btn btn-warning">
                  read more..
                </a>
              </div>
            </div>
            <div class="col d-flex align-items-start">
              <div>
                <h2>Latest News</h2>
                <p><strong>Posted Aug 08 2022</strong>
                  <br><span class="text-muted">the company reached its highest ever monthly profit.</span>
                  <br><strong>Posted Aug 08 2022</strong>
                  <br><span class="text-muted" >we have been voted the #1 producers in organic poultry products in the country for the secon time.</span>
                </p>
                <a href="#" class="btn btn-warning">
                  read more...
                </a>
              </div>
            </div>
          </div>
        </div>
      <div class="col-md-5 order-md-1" id="images-3">
         <div class="pictures" style="padding:40px">
            <img src="{% static "images/chicks.jpg" %}" alt="Chicks" id="chicks"/>
            <img src="{% static "images/chicken1.jpg" %}" alt="Chickens" id="chickens"/>
            <img src="{% static "images/Brown-eggs.jpg" %}" alt="Egg" id="eggs"/>
          </div>
      </div>
    </div>
      <div class="client pt-3 pb-3">
        <div class="container">
          <div class="row text-center">
            <div class="col-12">
              <h2 class="display-3 fw-bold text-dark">Testimonials</h2>
              <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 100px; height:3px;">
              <p class="p-text text-dark">What our clients are saying about us</p> 
            </div>
          </div>
          <div class="row align-items-md-center text-dark">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <div id="carousel" class="carousel slide" data-bs-ride="carousel">
              <!-- Wrapper for slides -->
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <div class="row p-4">
                      <div class="t-card">
                        <p class="lh-lg">
                          <i class="bi bi-quote" aria-hidden="true"></i> I have received the best equipment and training for my start-up chicken business. 
                            Thank you so much
                        </p>
                        <i class="fa fa-quote-right" aria-hidden="true"></i><br>
                      </div>
                      <div class="row">                    
                        <div class="col-sm-2 pt-3">
                          <img src="{% static "images/profile4.jpg" %}" class="rounded-circle img-responsive img-fluid">
                        </div>                    
                      <div class="col-sm-10">
                        <div class="arrow-down d-none d-lg-block"></div>
                        <h4><strong>Thandeka Zulu</strong></h4>
                        <p class="testimonial_subtitle"><span style="color:#FF9F29">Business Woman</span><br>
                          <span style="color:#FF9F29">ChickenIn</span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="carousel-item">
                  <div class="row p-4">
                    <div class="t-card">
                      <p class="lh-lg">
                        <i class="bi bi-quote" aria-hidden="true"></i> I always get the best organic poultry food from here, One of the best in the country 
                          if not the best 
                      </p>
                      <i class="fa fa-quote-right" aria-hidden="true"></i><br>
                    </div>
                    <div class="row">
                      <div class="col-sm-2 pt-4">
                        <img src="{% static "images/profile1.jpg" %}" class="rounded-circle img-responsive img-fluid">
                      </div>
                      <div class="col-sm-10">
                        <div class="arrow-down d-none d-lg-block"></div>
                        <h4><strong>John Doe</strong></h4>
                        <p class="testimonial_subtitle"><span style="color:#FF9F29">Lecture</span><br>
                          <span style="color:#FF9F29">University of Johannesburg</span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="carousel-item">
                  <div class="row p-4">
                    <div class="t-card">
                      <p class="lh-lg">
                        <i class="bi bi-quote" aria-hidden="true"></i>My egg bussiness has been booming fast, thanks to my number 1 egg suppliers who deliver 
                              quality after quality in time
                      </p>
                      <i class="fa fa-quote-right" aria-hidden="true"></i><br>
                    </div>
                    <div class="row text-lg-start">
                      <div class="col-sm-2 pt-4 align-items-center">
                        <img src="{% static "images/profile3.jpg" %}" class="rounded-circle img-responsive img-fluid">
                      </div>
                      <div class="col-sm-10">
                        <div class="arrow-down d-none d-md-block"></div>
                        <h4><strong>Hellen Smith</strong></h4>
                        <p class="testimonial_subtitle"><span>Business Woman</span><br>
                          <span>Just Eggs</span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Carousel wrapper -->
      {% comment %} Hero javascripts {% endcomment %}
      <script type="text/javascript" src="{% static 'js/object-fit-videos.js'%}"></script>
      <script type="text/javascript" src="{% static 'js/app.js'%}"></script>
  </section>
</main>
{% endblock %}

templates/store/lessons.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% load static %}
{% block title %}Lessons{% endblock %}

{% block content %}

<main>
    <h1>Hello world from Lessons page </h1>
</main>

{% endblock %}